SELECT C.AUTHOR_ID, C.AUTHOR_NAME, D.CATEGORY, D.SALES AS TOTAL_SALES
FROM AUTHOR AS C
INNER JOIN (
    SELECT A.AUTHOR_ID, A.CATEGORY, SUM(B.SALES*A.PRICE) AS SALES
    FROM BOOK AS A
    INNER JOIN BOOK_SALES AS B
    ON A.BOOK_ID = B.BOOK_ID
    WHERE YEAR(B.SALES_DATE) = 2022 AND MONTH(B.SALES_DATE) = 1
    GROUP BY A.AUTHOR_ID, A.CATEGORY
) AS D
ON C.AUTHOR_ID = D.AUTHOR_ID
ORDER BY C.AUTHOR_ID, D.CATEGORY DESC;

