-- 코드를 작성해주세요
SELECT C.ITEM_ID, C.ITEM_NAME, C.RARITY
FROM (
    SELECT A.ITEM_ID, A.ITEM_NAME, A.RARITY, B.PARENT_ITEM_ID
    FROM ITEM_INFO AS A
    LEFT JOIN ITEM_TREE AS B
    ON A.ITEM_ID = B.PARENT_ITEM_ID
) AS C
WHERE C.PARENT_ITEM_ID IS NULL
ORDER BY C.ITEM_ID DESC;

