SELECT A.CAR_ID, A.CAR_TYPE, ROUND(A.DAILY_FEE * 30 * ((100 - C.DISCOUNT_RATE) / 100), 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS A
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B ON A.CAR_ID = B.CAR_ID
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS C ON A.CAR_TYPE = C.CAR_TYPE
WHERE A.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE >= '20221101' AND START_DATE <= '20221130'
) AND C.DURATION_TYPE LIKE '30%' AND A.CAR_TYPE IN ('SUV', '세단')
GROUP BY A.CAR_ID
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, A.CAR_TYPE, A.CAR_ID DESC;