SELECT A.ID,
    CASE
        WHEN A.COLONY_SIZE = 1 THEN 'CRITICAL'
        WHEN A.COLONY_SIZE = 2 THEN 'HIGH'
        WHEN A.COLONY_SIZE = 3 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS 'COLONY_NAME'
FROM (
    SELECT ID, NTILE(4)
    OVER(ORDER BY SIZE_OF_COLONY DESC) AS 'COLONY_SIZE'
    FROM ECOLI_DATA
) AS A
ORDER BY A.ID;
