# -- 코드를 입력하세요
SELECT C.ANIMAL_ID, D.NAME
FROM (
    SELECT A.ANIMAL_ID
    FROM ANIMAL_OUTS AS A
    LEFT JOIN ANIMAL_INS AS B
    ON A.ANIMAL_ID = B.ANIMAL_ID
    WHERE INTAKE_CONDITION IS NULL
) AS C
INNER JOIN ANIMAL_OUTS AS D
ON C.ANIMAL_ID = D.ANIMAL_ID
ORDER BY C.ANIMAL_ID;