-- 코드를 입력하세요
SELECT C.YEAR, C.MONTH, C.COUNT AS PURCHASED_USERS, ROUND(C.COUNT / D.COUNT, 1) AS PUCHASED_RATIO
FROM (
    SELECT YEAR(A.SALES_DATE) AS YEAR, MONTH(A.SALES_DATE) AS MONTH, COUNT(DISTINCT A.USER_ID) AS COUNT
    FROM ONLINE_SALE AS A
    INNER JOIN USER_INFO AS B
    ON A.USER_ID = B.USER_ID
    WHERE YEAR(B.JOINED) = 2021
    GROUP BY YEAR(A.SALES_DATE), MONTH(A.SALES_DATE)
) AS C
JOIN (SELECT COUNT(*) AS COUNT
FROM USER_INFO
WHERE YEAR(JOINED) = 2021) AS D
ORDER BY C.YEAR, C.MONTH;
