-- 1세대 대장균 쿼리 생성
WITH RECURSIVE CTE AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT A.ID, A.PARENT_ID, CTE.GENERATION + 1
    FROM CTE INNER JOIN ECOLI_DATA AS A
    ON CTE.ID = A.PARENT_ID
)


SELECT COUNT(*) AS COUNT, GENERATION
FROM CTE
WHERE ID NOT IN (
    SELECT DISTINCT PARENT_ID
        FROM CTE
        WHERE PARENT_ID IS NOT NULL
)
GROUP BY GENERATION
ORDER BY GENERATION