-- 코드를 입력하세요
SELECT C.FLAVOR
FROM (
    SELECT A.FLAVOR, SUM(A.TOTAL_ORDER + B.TOTAL_ORDER) AS TOTAL_ORDER
    FROM FIRST_HALF AS A
    LEFT JOIN JULY AS B
    ON A.FLAVOR = B.FLAVOR
    GROUP BY A.FLAVOR
    UNION
    SELECT A.FLAVOR, SUM(A.TOTAL_ORDER + B.TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY AS A
    LEFT JOIN FIRST_HALF AS B
    ON A.FLAVOR = B.FLAVOR
    GROUP BY A.FLAVOR
) AS C
ORDER BY C.TOTAL_ORDER DESC
LIMIT 3;
