-- 코드를 작성해주세요
SELECT A.ID, A.EMAIL, A.FIRST_NAME, A.LAST_NAME
FROM DEVELOPERS AS A
WHERE A.SKILL_CODE & (
    SELECT SUM(CODE) AS CODE
    FROM SKILLCODES
    WHERE CATEGORY LIKE 'Front%'
    GROUP BY CATEGORY
)
ORDER BY A.ID


