SELECT B.DATE AS YEAR, (B.MAX_S - A.SIZE_OF_COLONY) AS YEAR_DEV, A.ID
FROM ECOLI_DATA AS A
LEFT JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) AS DATE, MAX(SIZE_OF_COLONY) AS MAX_S
    FROM ECOLI_DATA
    GROUP BY DATE
) AS B
ON YEAR(A.DIFFERENTIATION_DATE) = B.DATE
ORDER BY B.DATE, YEAR_DEV
