# -- 점수, 사번, 성명, 직책, 이메일
# SELECT MAX(C.SCORE) AS SCORE, C.EMP_NO, C.EMP_NAME, C.POSITION, C.EMAIL
# FROM (
#     SELECT A.EMP_NO, SUM(A.SCORE) AS SCORE, B.EMP_NAME, B.POSITION, B.EMAIL
#     FROM HR_GRADE AS A
#     INNER JOIN HR_EMPLOYEES AS B
#     ON A.EMP_NO = B.EMP_NO
#     WHERE YEAR = 2022
#     GROUP BY EMP_NO
# ) AS C

SELECT SUM(A.SCORE) AS SCORE, A.EMP_NO, B.EMP_NAME, B.POSITION, B.EMAIL
FROM HR_GRADE AS A
INNER JOIN HR_EMPLOYEES AS B
ON A.EMP_NO = B.EMP_NO
WHERE YEAR = 2022
GROUP BY EMP_NO
ORDER BY SCORE DESC
LIMIT 1;
