-- 부서 ID, 영문 부서명, 평균 연봉
SELECT A.DEPT_ID, B.DEPT_NAME_EN, ROUND(AVG(A.SAL), 0) AS AVG_SAL
FROM HR_EMPLOYEES AS A
INNER JOIN HR_DEPARTMENT AS B
ON A.DEPT_ID = B.DEPT_ID
GROUP BY A.DEPT_ID
ORDER BY AVG_SAL DESC;